//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// <h2><span class="mw-headline" id="History">History</span></h2>
/// <table class="HistoryTable" border="1">
/// <tbody>
/// <tr>
///   <th>Author</th>
///   <th>Date</th>
///   <th>Description</th>
/// </tr>
/// <tr>
///   <td>Michael J. Findler</td>
///   <td>21 March 2019</td>
///   <td>Testing the comments help section</td>
/// </tr>
/// </tbody></table>
/// </summary>
/*public class ButtonManager
{
	private ModeManager modeMgr
	{
		get;
		set;
	}

	private TimeManager timeMgr
	{
		get;
		set;
	}

	public ButtonManager()
	{
	}

	public virtual void DoIncrementHour()
	{
		throw new System.NotImplementedException();
	}

    /// <summary>
    /// Does the increment minute.  If minute >=60, then hour++ and minute = 0
    /// </summary>
    /// <exception cref="System.NotImplementedException"></exception>
    public virtual void DoIncrementMinute()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DoSnooze()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DoSetTime()
	{
		throw new System.NotImplementedException();
	}

    /// <summary>
    /// Does the set alarm.
    /// </summary>
    /// <exception cref="System.NotImplementedException"></exception>
    public virtual void DoSetAlarm()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DoAlarmOn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DoAlarmOff()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetModeManager(ModeManager newModeMgr)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetTimeManager(TimeManager newTimeMgr)
	{
		throw new System.NotImplementedException();
	}

}*/

